name: "daily alerts"

on:
  push:
    branches:
      - main
  schedule:
    - cron: "10 21 * * 1,2,3,4,5,6"

jobs:
  backup:
    runs-on: ubuntu-latest
    name: Backup
    timeout-minutes: 25
    env:
      OPENAI_API_KEYS: ${{ secrets.OPENAI_API_KEYS }}
      TOKEN: ${{ secrets.TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Pull remote changes
        run: |
          git config --global user.email "lixinru142857@gmail.com"
          git config --global user.name "HAL149"
          git stash --include-untracked
          git pull --rebase origin main
          git stash pop || true

      # 生成 Markdown 文件并提交
      - name: Generate markdown file
        run: python main.py --mode generate

      # 创建 Issue（基于已提交的 Markdown 文件）
      - name: Create Issue from markdown file
        run: python main.py --mode create-issue


      - name: Commit generated markdown file
        run: |
          git config --global user.email "lixinru142857@gmail.com"
          git config --global user.name "HAL149"
          git add export/*.md
          git commit -m "Automated snapshot of markdown file" || echo "No changes to commit"
          git push origin main



